version: "3.8"

services: 
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: govac
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: govac_password
    volumes: 
       - govac_postgresdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  govac_postgresdata:
    name: govac_postgresdata